### ISSUE TITLE
stderr File descriptor leak

### ISSUE THREAD

**Issue by ThrosturX** [opsgenie/oec#14]
OEC is leaking file descriptors. `lsof` output was full of lines such as the following:

```
OpsgenieE   2185 79588                opsgenie  938w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  939w      REG              253,0   1012227    1255847 /home/opsgenie/oec/logs/closeErr.txt
OpsgenieE   2185 79588                opsgenie  940w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  941w      REG              253,0   1012227    1255847 /home/opsgenie/oec/logs/closeErr.txt
OpsgenieE   2185 79588                opsgenie  942w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  943w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  944w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  945w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  946w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  947w      REG              253,0   1012227    1255847 /home/opsgenie/oec/logs/closeErr.txt
OpsgenieE   2185 79588                opsgenie  948w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
OpsgenieE   2185 79588                opsgenie  949w      REG              253,0    489814    1266478 /home/opsgenie/oec/logs/createErr.txt
```
The problem has been identified here: https://github.com/opsgenie/oec/blob/5e83474887e46404c833c7abdf75efd7e2536a28/runbook/executor.go#L52-L54
The issue is that an `io.MultiWriter` does not implement `io.Closer`. Although the buffer.Bytes does not need Closing, the lumberjack logger is an `io.Closer` and needs to be closed:
https://godoc.org/gopkg.in/natefinch/lumberjack.v2#Logger.Close

I have implemented a quick-fix and sent a pull request.

**Comment by metehanozturk** [comment]
Which version do you use? The problem is solved with the 1.0.3 version (commit version: 5e83474887e46404c833c7abdf75efd7e2536a28). After the new version, only one lumberjack being instantiated for each mapped action and OEC are re-using it every time. Although we tried to create and close the logger every single triggered action, lumberjack continues to leak. I guess lumberjack has a memory leak issue itself and we track the news from the library. Now, we alternatively create limited lumberjack, use constantly and do not close it. If you can confirm the version, we can get the clue to understanding whether it caused by the same problem or not.
Thanks.

**Comment by ThrosturX** [comment]
Thanks for the swift feedback. I will report back at the earliest opportunity.

**Comment by ThrosturX** [comment]
Hi @metehanozturk, thank you for getting back to me.
I've verified the issue was reproduced on version 1.0.1, we'll try upgrading soon and report back if the problem persists.
In any case, you're right about Lumberjack leaking: https://github.com/natefinch/lumberjack/issues/81

I'd still like to point out that if you do decide to close the logger at some point, you can't use an io.MultiWriter and expect the exec.Cmd to close the underlying writers.
I will re-open the issue or create a new one if we can reproduce a similar issue in the new version.
