### ISSUE TITLE
OEC Repository

### ISSUE THREAD

**Issue by tobzsc** [opsgenie/oec#16]
It would be nice to have a repository for RPM and DEB bases distributions with the latest versions. This would make oec upgrades much easier.

**Comment by cglrkn** [comment]
Thanks for the input. We have tasks for builds on our side and we provide the packages to customers.

**Comment by tobzsc** [comment]
Have you understood my request? I am asking for a repository to check out the latest packages.

**Comment by 5nafu** [comment]
I would like to second the request for a proper debian and redhat repository to enable automatic update of the oec.

Supplying packages via the documentation can not be automated on client side.

**Comment by Ray-B** [comment]
Worth pointing out that the current implementation of links in the documentation for latest also make it difficult to pin versions. Version pinning would be very helpful, if not essential, for many.

**Comment by metehanozturk** [comment]
We are using [oec-scripts](https://github.com/opsgenie/oec-scripts/releases) repository to provide releases for each integration package, and vanilla edition as well. Also, the packages that contain only executable are [here](https://github.com/opsgenie/oec-scripts/releases). Does this solve the problem?
