### ISSUE TITLE
Debug recieved messages

### ISSUE THREAD

**Issue by freeseacher** [opsgenie/oec#5]
Hi. 
Working with OEC found that it will be pretty helpfull if it will dump received messages. Probably with Extended debug or so on

**Comment by metehanozturk** [comment]
Received messages are accessible from the custom scripts, and stdout of scripts can be printed to any file you want by configuring the json file of OEC. That might be work for your case.

Besides that, your suggestion is also meaningful. There can be a special configuration field to print all received messages to separate file optionally. 

Thanks for the feedback, this feature issue will probably be handled in our next sprint.

**Comment by freeseacher** [comment]
yep i already found the way i can dump recieved json for known mappedAction. but it was pretty unstraight way. 
I was looking for docs how mappedAction is called to attach them to my job but never find any glue. 
i think that here is the right place https://docs.opsgenie.com/docs/oec-configuration

**Comment by metehanozturk** [comment]
OEC integration uses directly actual actions (e.g. "Create", "Close", "Acknowledge", etc.), other integrations will use primarily "mappedAction" related with themselves (e.g. "addCommentToIssue", "createIssue", etc. for Jira integration). "actionMappings" is tpye of map that contains those actions with details.

Doc will be revised to specify the usage of mapped actions more precisely. Example configurations that contain the mappedAction names for each integration will be presented soon.
