### ISSUE TITLE
is project dead?

### ISSUE THREAD

**Issue by freeseacher** [opsgenie/oec#52]
no commits, no releases, no pull request or even answers for the issues for more than a year...

**Comment by XtremeOwnageDotCom** [comment]
Rather curious to know myself.

**Comment by brtduvally** [comment]
Came here to ask the same question +1

**Comment by akovov** [comment]
but at least it works

**Comment by metehanozturk** [comment]
No, Opsgenie Edge Connector (and other tools) development isn’t dead. We’ve recently standardized our feature request/suggestion process to use our public issue tracker, [jira.atlassian.com](http://jira.atlassian.com/), where you can find open Suggestions and Bugs.
If you are experiencing an issue with OEC, or if you want to raise a new bug or suggestion you can reach out [Opsgenie support.](https://support.atlassian.com/contact/#/)
